title: "Anna Laura Erdei"
description: "Chemical ecology • insect olfaction • visual art"
theme: jekyll-theme-cayman

header_pages:
  - cv.md
  - publications.md
  - projects.md
  - teaching.md
  - art/index.md
