title: "Anna Laura Erdei"
description: "Chemical ecology • insect olfaction • visual art"

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: contrast

plugins:
  - jekyll-include-cache

header_pages:
  - cv.md
  - publications.md
  - projects.md
  - teaching.md
  - art/index.md
